### ISSUE TITLE
Make it possible to avoid the `rustc_version` and `semver` build dependencies

### ISSUE THREAD

**Issue by briansmith** [japaric/cast.rs#35]
Hi, I'd like to use `cast.rs` but I'd also like to minimize my dependency tree. I noticed that `rustc_version` seems to be used primarily to decide whether to support 128-bit types. But, 128-bit types have been in stable Rust for years. I think it would be a better trade-off to break compatibility with the ancient versions of Rust with a new version that eliminates this conditional check. I would be happy to submit a PR that does this if you agree this makes sense.

**Comment by japaric** [comment]
Hi, I think that sounds reasonable. I'd be OK with doing a 0.3.0 release that drops the rustc-version build dep, removes the x128 Cargo feature and removes the MSRV policy text from the docs. Feel free to submit a PR that does any part of that and I'll follow up with a release. Thanks for bringing this up!

**Comment by briansmith** [comment]
PR #37 fixes this.

**Comment by japaric** [comment]
done in #37
